---
- name: Converge
  hosts: all
  become: True

  # set testing variables
  vars:
    hosts_hosts:
      - name: "foo1"
        ipv4: "1.2.3.4"
        ipv6: "2001:23:345:0::34"
      - name: "baa2"
        ipv4: "234.123.3.234"
        ipv6:
      - name: "lala3"
        ipv4:
        ipv6: "fe76:23:1234:4567::123"


  ## run role ##
  roles:
    - role: hosts-file


  # test / verify results
  tasks:
    - slurp:
        src: /etc/hosts
      register: hosts_file

    - set_fact:
        hosts_file_content: "{{ hosts_file['content'] |b64decode }}"

    - debug:
        msg: "{{ hosts_file_content.split('\n') }}"
