---
- name: Converge
  hosts: all
  become: True

  # variables set in molecule.yml inventory

  ## run role ##
  roles:
    - role: hosts-file

#  # verify results
#  tasks:
#    - slurp:
#        src: /etc/hosts
#      register: hosts_file
#
#    - set_fact:
#        hosts_file_content: "{{ hosts_file['content'] |b64decode }}"
#
#    - debug:
#        msg: "{{ hosts_file_content.split('\n') }}"
